import { FormEvent, useCallback, useEffect, useState } from "react";
import type { ActiveConnection, AuditEntry, Device, DeviceTokenResponse, GeoLocation, MetricsSnapshot, Tunnel, UpdateTunnelRequest } from "@tunnelbridge/api-types";
import { Activity, Box, Cable, Check, Clipboard, Gauge, KeyRound, LogOut, Plus, Radio, Settings, Shield, Trash2, Users, X } from "lucide-react";

type Page = "overview" | "devices" | "tunnels" | "connections" | "audit" | "settings";
interface ServerSettings { port_start: number; port_end: number; ticket_ttl_seconds: number; connect_timeout_seconds: number; idle_timeout_seconds: number; audit_retention_days: number }
let csrfToken = "";

async function api<T>(path: string, options: RequestInit = {}): Promise<T> {
  const headers = new Headers(options.headers);
  if (options.body) headers.set("Content-Type", "application/json");
  if (options.method && !["GET", "HEAD"].includes(options.method)) headers.set("X-CSRF-Token", csrfToken);
  const response = await fetch(`/api/v1${path}`, { ...options, headers, credentials: "same-origin" });
  if (!response.ok) {
    const error = await response.json().catch(() => ({ message: response.statusText }));
    throw new Error(error.message ?? "请求失败");
  }
  if (response.status === 204) return undefined as T;
  return response.json();
}

const zeroMetrics: MetricsSnapshot = { online_agents: 0, active_connections: 0, bytes_up: 0, bytes_down: 0, rejected_connections: 0, failed_connections: 0 };
const formatBytes = (value: number) => value < 1024 ? `${value} B` : value < 1024 ** 2 ? `${(value / 1024).toFixed(1)} KB` : value < 1024 ** 3 ? `${(value / 1024 ** 2).toFixed(1)} MB` : `${(value / 1024 ** 3).toFixed(2)} GB`;
function countryFlag(code: string) { const normalized = code.trim().toUpperCase(); if (!/^[A-Z]{2}$/.test(normalized)) return "🌐"; return [...normalized].map((letter) => String.fromCodePoint(letter.charCodeAt(0) + 127397)).join(""); }
function countryLabel(location: GeoLocation) { try { return new Intl.DisplayNames(["zh-CN"], { type: "region" }).of(location.country_code) ?? location.country_name; } catch { return location.country_name; } }
function CountryBadge({ location }: { location?: GeoLocation | null }) { if (!location) return <span className="source-location unknown" title="暂时无法解析来源国家"><span aria-hidden="true">🌐</span><span>未知来源</span></span>; return <span className="source-location" title={`${location.country_name} · ${location.country_code}`}><span aria-hidden="true">{countryFlag(location.country_code)}</span><span>{countryLabel(location)}</span></span>; }

function App() {
  const [username, setUsername] = useState<string | null>(null);
  const [checking, setChecking] = useState(true);
  useEffect(() => { api<{ username: string; csrf_token: string }>("/auth/me").then((me) => { csrfToken = me.csrf_token; setUsername(me.username); }).catch(() => undefined).finally(() => setChecking(false)); }, []);
  if (checking) return <div className="boot"><div className="radar" /></div>;
  if (!username) return <Login onLogin={(name, csrf) => { csrfToken = csrf; setUsername(name); }} />;
  return <Console username={username} onLogout={() => { csrfToken = ""; setUsername(null); }} />;
}

function Login({ onLogin }: { onLogin: (name: string, csrf: string) => void }) {
  const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { const result = await api<{ username: string; csrf_token: string }>("/auth/login", { method: "POST", body: JSON.stringify({ username: "admin", password }) }); onLogin(result.username, result.csrf_token); } catch (e) { setError(String(e).replace("Error: ", "")); } finally { setBusy(false); } }
  return <main className="login-screen"><div className="login-art"><div className="topography"/><div className="coordinates">TB / CONTROL<br/>35.6762° N<br/>139.6503° E</div><div className="login-wordmark"><Logo/><span>RELAY<br/>CONTROL</span></div><h1>Private routes.<br/><em>Public reach.</em></h1><p>管理你的设备、端口和访问边界。</p></div><form className="login-form" onSubmit={submit}><div><p className="kicker">AUTHORIZED ACCESS ONLY</p><h2>管理员登录</h2><p>使用首次部署时设置的管理员密码。</p></div><label>用户名<input value="admin" disabled /></label><label>密码<input type="password" value={password} onChange={(e) => setPassword(e.target.value)} autoFocus required /></label>{error && <p className="form-error">{error}</p>}<button className="primary" disabled={busy}><KeyRound/>{busy ? "正在验证" : "进入控制台"}</button><small><Shield/> 会话使用 Secure、HttpOnly Cookie 保护</small></form></main>;
}

function Console({ username, onLogout }: { username: string; onLogout: () => void }) {
  const [page, setPage] = useState<Page>("overview"); const [metrics, setMetrics] = useState(zeroMetrics); const [devices, setDevices] = useState<Device[]>([]); const [tunnels, setTunnels] = useState<Tunnel[]>([]); const [connections, setConnections] = useState<ActiveConnection[]>([]); const [audit, setAudit] = useState<AuditEntry[]>([]); const [settings, setSettings] = useState<ServerSettings | null>(null); const [newToken, setNewToken] = useState<DeviceTokenResponse | null>(null); const [showDevice, setShowDevice] = useState(false); const [notice, setNotice] = useState("");
  const refresh = useCallback(async () => { try { const [m,d,t,c,a,s] = await Promise.all([api<MetricsSnapshot>("/admin/metrics"), api<Device[]>("/admin/devices"), api<Tunnel[]>("/admin/tunnels"), api<ActiveConnection[]>("/admin/connections"), api<AuditEntry[]>("/admin/audit?limit=100"), api<ServerSettings>("/admin/settings")]); setMetrics(m); setDevices(d); setTunnels(t); setConnections(c); setAudit(a); setSettings(s); } catch (e) { setNotice(String(e)); } }, []);
  useEffect(() => { void refresh(); const id = window.setInterval(refresh, 5000); return () => clearInterval(id); }, [refresh]);
  async function logout() { await api<void>("/auth/logout", { method: "POST" }).catch(() => undefined); onLogout(); }
  async function revoke(device: Device) { if (!confirm(`撤销设备“${device.name}”的令牌？`)) return; try { await api(`/admin/devices/${device.id}`, { method: "DELETE" }); await refresh(); } catch(e) { setNotice(String(e)); } }
  async function updateTunnel(tunnel: Tunnel, request: UpdateTunnelRequest) { try { await api(`/admin/tunnels/${tunnel.id}`, { method: "PATCH", body: JSON.stringify(request) }); await refresh(); } catch(e) { setNotice(String(e)); } }
  async function deleteTunnel(tunnel: Tunnel) { if (!confirm(`删除隧道“${tunnel.name}”？`)) return; try { await api(`/admin/tunnels/${tunnel.id}`, { method: "DELETE" }); await refresh(); } catch(e) { setNotice(String(e)); } }
  return <div className="console"><aside><Logo/><div className="node-state"><span/><div><strong>RELAY ONLINE</strong><small>{metrics.online_agents} AGENTS LINKED</small></div></div><nav><Nav active={page==="overview"} icon={<Gauge/>} label="总览" onClick={()=>setPage("overview")}/><Nav active={page==="devices"} icon={<Users/>} label="设备与令牌" onClick={()=>setPage("devices")}/><Nav active={page==="tunnels"} icon={<Cable/>} label="隧道" onClick={()=>setPage("tunnels")}/><Nav active={page==="connections"} icon={<Radio/>} label="活动连接" onClick={()=>setPage("connections")}/><Nav active={page==="audit"} icon={<Activity/>} label="审计记录" onClick={()=>setPage("audit")}/><Nav active={page==="settings"} icon={<Settings/>} label="服务设置" onClick={()=>setPage("settings")}/></nav><div className="account"><span>{username.slice(0,1).toUpperCase()}</span><div><strong>{username}</strong><small>SOLE ADMIN</small></div><button onClick={logout} title="退出"><LogOut/></button></div></aside>
    <main><header><div><p className="kicker">TUNNELBRIDGE / {page.toUpperCase()}</p><h1>{({overview:"运行总览",devices:"设备与令牌",tunnels:"隧道管理",connections:"活动连接",audit:"审计记录",settings:"服务设置"})[page]}</h1></div>{page==="devices"&&<button className="primary" onClick={()=>setShowDevice(true)}><Plus/>创建设备</button>}</header>
      {page==="overview"&&<Overview metrics={metrics} devices={devices} tunnels={tunnels} audit={audit}/>} {page==="devices"&&<Devices devices={devices} onRevoke={revoke}/>} {page==="tunnels"&&<Tunnels tunnels={tunnels} onUpdate={updateTunnel} onDelete={deleteTunnel}/>} {page==="connections"&&<Connections connections={connections} tunnels={tunnels}/>} {page==="audit"&&<Audit entries={audit}/>} {page==="settings"&&<SettingsPage settings={settings} onPasswordChanged={onLogout} onError={setNotice}/>}</main>
    {showDevice&&<CreateDevice onClose={()=>setShowDevice(false)} onCreated={async(token)=>{setShowDevice(false);setNewToken(token);await refresh();}} onError={setNotice}/>} {newToken&&<TokenReveal value={newToken} onClose={()=>setNewToken(null)}/>} {notice&&<div className="notice">{notice}<button onClick={()=>setNotice("")}><X/></button></div>}</div>;
}

function Logo(){return <div className="logo"><Box/><strong>TB</strong></div>}
function Nav({active,icon,label,onClick}:{active:boolean;icon:React.ReactNode;label:string;onClick:()=>void}){return <button className={active?"active":""} onClick={onClick}>{icon}<span>{label}</span></button>}

function Overview({metrics,devices,tunnels,audit}:{metrics:MetricsSnapshot;devices:Device[];tunnels:Tunnel[];audit:AuditEntry[]}){return <div className="content enter"><div className="metric-grid"><Metric label="在线代理" value={metrics.online_agents} unit={`${devices.length} registered`} accent/><Metric label="活动连接" value={metrics.active_connections} unit="live tcp sessions"/><Metric label="已接收" value={formatBytes(metrics.bytes_down)} unit="relay to local"/><Metric label="已发送" value={formatBytes(metrics.bytes_up)} unit="local to relay"/></div><div className="overview-grid"><section className="panel"><div className="panel-head"><div><p className="kicker">ROUTE MATRIX</p><h2>隧道状态</h2></div><span>{tunnels.filter(t=>t.status==="online").length} ONLINE</span></div>{tunnels.length?tunnels.slice(0,6).map(t=><div className="route" key={t.id}><i className={t.status}/><strong>{t.name}</strong><code>:{t.remote_port}</code><span>{t.status.replace("_"," ")}</span></div>):<Empty text="等待设备创建第一条隧道"/>}</section><section className="panel"><div className="panel-head"><div><p className="kicker">LATEST EVENTS</p><h2>安全活动</h2></div></div>{audit.length?audit.slice(0,6).map(a=><div className="audit-mini" key={a.id}><time>{new Date(a.created_at).toLocaleTimeString()}</time><div><strong>{a.action}</strong><span>{a.detail}</span></div></div>):<Empty text="暂无审计记录"/>}</section></div></div>}
function Metric({label,value,unit,accent}:{label:string;value:string|number;unit:string;accent?:boolean}){return <div className={`metric ${accent?"accent":""}`}><span>{label}</span><strong>{value}</strong><code>{unit}</code></div>}
function Devices({devices,onRevoke}:{devices:Device[];onRevoke:(d:Device)=>void}){return <div className="content enter panel table"><div className="tr th"><span>设备</span><span>状态</span><span>最后在线</span><span>创建时间</span><span/></div>{devices.length?devices.map(d=><div className="tr" key={d.id}><div className="device"><span>{d.name.slice(0,1).toUpperCase()}</span><div><strong>{d.name}</strong><code>{d.id.slice(0,8)}</code></div></div><b className={d.revoked?"revoked":d.online?"online":"offline"}>{d.revoked?"已撤销":d.online?"在线":"离线"}</b><span>{d.last_seen_at?new Date(d.last_seen_at).toLocaleString():"从未连接"}</span><span>{new Date(d.created_at).toLocaleDateString()}</span><button className="danger" disabled={d.revoked} onClick={()=>onRevoke(d)}><Trash2/></button></div>):<Empty text="尚未注册设备"/>}</div>}
function Tunnels({tunnels,onUpdate,onDelete}:{tunnels:Tunnel[];onUpdate:(t:Tunnel,r:UpdateTunnelRequest)=>void;onDelete:(t:Tunnel)=>void}){return <div className="content enter panel table"><div className="tr tunnel-th"><span>映射</span><span>设备</span><span>访问策略</span><span>状态</span><span/></div>{tunnels.length?tunnels.map(t=><div className="tr tunnel-tr" key={t.id}><div><strong>{t.name}</strong><code>{t.local_host}:{t.local_port} → :{t.remote_port}</code></div><code>{t.agent_id.slice(0,8)}</code><span className={`badge ${t.access_mode}`}>{t.access_mode==="public"?"公开":`${t.allowed_cidrs.length} CIDR`}</span><b className={t.status}>{t.status.replace("_"," ")}</b><div className="actions"><button className={`toggle ${t.enabled?"on":""}`} aria-label="切换隧道" onClick={()=>onUpdate(t,{enabled:!t.enabled})}><span/></button><button className="danger" onClick={()=>onDelete(t)}><Trash2/></button></div></div>):<Empty text="尚未创建隧道"/>}</div>}
function Connections({connections,tunnels}:{connections:ActiveConnection[];tunnels:Tunnel[]}){const names=new Map(tunnels.map(t=>[t.id,t.name]));return <div className="content enter panel table"><div className="tr connection-th"><span>隧道</span><span>来源</span><span>建立时间</span><span>上行 / 下行</span></div>{connections.length?connections.map(c=><div className="tr connection-th" key={c.id}><strong>{names.get(c.tunnel_id)??c.tunnel_id.slice(0,8)}</strong><div className="source-cell"><code>{c.peer_addr}</code><CountryBadge location={c.peer_location}/></div><span>{new Date(c.opened_at).toLocaleString()}</span><code>{formatBytes(c.bytes_up)} / {formatBytes(c.bytes_down)}</code></div>):<Empty text="当前没有活动连接"/>}</div>}
function Audit({entries}:{entries:AuditEntry[]}){return <div className="content enter panel audit-list">{entries.length?entries.map(e=><div className="audit-row" key={e.id}><time>{new Date(e.created_at).toLocaleString()}</time><span/><div><strong>{e.action}</strong><p>{e.detail}</p><code>{e.subject}</code></div></div>):<Empty text="暂无审计记录"/>}</div>}
function SettingsPage({settings,onPasswordChanged,onError}:{settings:ServerSettings|null;onPasswordChanged:()=>void;onError:(m:string)=>void}){const[current,setCurrent]=useState("");const[next,setNext]=useState("");const[confirmPassword,setConfirmPassword]=useState("");const[busy,setBusy]=useState(false);async function submit(e:FormEvent){e.preventDefault();if(next!==confirmPassword){onError("两次输入的新密码不一致");return}setBusy(true);try{await api<void>("/admin/password",{method:"PATCH",body:JSON.stringify({current_password:current,new_password:next})});onPasswordChanged()}catch(error){onError(String(error))}finally{setBusy(false)}}return <div className="content enter settings-layout"><section className="panel settings-panel"><p className="kicker">DEPLOYMENT LIMITS</p><h2>运行限制</h2><p>这些参数来自服务端环境变量，修改后需要重新部署容器。</p><dl><div><dt>公网端口池</dt><dd>{settings?`${settings.port_start} — ${settings.port_end}`:"—"}</dd></div><div><dt>票据有效期</dt><dd>{settings?.ticket_ttl_seconds??"—"} 秒</dd></div><div><dt>连接等待时间</dt><dd>{settings?.connect_timeout_seconds??"—"} 秒</dd></div><div><dt>连接空闲超时</dt><dd>{settings?.idle_timeout_seconds??"—"} 秒</dd></div><div><dt>审计保留期</dt><dd>{settings?.audit_retention_days??"—"} 天</dd></div></dl></section><form className="panel settings-panel password" onSubmit={submit}><p className="kicker">ADMIN CREDENTIAL</p><h2>修改管理员密码</h2><p>修改后所有管理会话都会失效，需要重新登录。</p><label>当前密码<input type="password" value={current} onChange={e=>setCurrent(e.target.value)} required/></label><label>新密码<input type="password" minLength={12} value={next} onChange={e=>setNext(e.target.value)} required/></label><label>确认新密码<input type="password" minLength={12} value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} required/></label><button className="primary" disabled={busy}>{busy?"正在更新":"更新密码"}</button></form></div>}
function Empty({text}:{text:string}){return <div className="empty"><Radio/><span>{text}</span></div>}

function CreateDevice({onClose,onCreated,onError}:{onClose:()=>void;onCreated:(v:DeviceTokenResponse)=>void;onError:(m:string)=>void}){const[name,setName]=useState("");const[busy,setBusy]=useState(false);async function submit(e:FormEvent){e.preventDefault();setBusy(true);try{onCreated(await api("/admin/devices",{method:"POST",body:JSON.stringify({name})}));}catch(error){onError(String(error));}finally{setBusy(false)}}return <div className="modal"><form onSubmit={submit}><button type="button" className="close" onClick={onClose}><X/></button><Users/><p className="kicker">REGISTER AGENT</p><h2>创建设备令牌</h2><p>令牌只会展示一次。请立即保存到对应 Mac。</p><label>设备名称<input value={name} onChange={e=>setName(e.target.value)} placeholder="Office Mac mini" autoFocus required maxLength={80}/></label><button className="primary" disabled={busy}>{busy?"正在创建":"创建令牌"}</button></form></div>}
function TokenReveal({value,onClose}:{value:DeviceTokenResponse;onClose:()=>void}){const[copied,setCopied]=useState(false);async function copy(){await navigator.clipboard.writeText(value.token);setCopied(true)}return <div className="modal"><div className="token-card"><Shield/><p className="kicker">ONE-TIME SECRET</p><h2>保存设备令牌</h2><p>关闭后将无法再次查看。如令牌遗失，请撤销设备并重新创建。</p><code>{value.token}</code><button className="primary" onClick={copy}>{copied?<Check/>:<Clipboard/>}{copied?"已复制":"复制令牌"}</button><button className="link" onClick={onClose}>我已安全保存</button></div></div>}

export default App;
